version: '3'
services:
  grafana:
    image: grafana/grafana:6.5.2
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana
      - .:/var/lib/grafana/plugins/cassandra
    environment:
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource
  cassandra:
    image: datastax/dse-server:6.7.4
    ports:
      - "9042:9042"
    volumes:
      - /var/lib/cassandra
    environment:
      DS_LICENSE: accept
  studio:
    image: datastax/dse-studio:6.7.0
    ports:
      - "9091:9091"
    depends_on:
      - cassandra
    environment:
      DS_LICENSE: accept
