version: '3'
services:
  grafana:
    image: grafana/grafana:6.5.2
    ports:
      - "3000:3000"
    environment:
      GF_LOG_LEVEL: debug
    volumes:
      - /var/lib/grafana
      - .:/var/lib/grafana/plugins/cassandra
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    volumes:
      - /var/lib/cassandra
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
