[[constraint]]
  name = "github.com/bitly/go-simplejson"
  version = "0.5.0"

[[constraint]]
  name = "github.com/grafana/grafana_plugin_model"
  branch = "master"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "github.com/gocql/gocql"
  branch = "master"
