[[constraint]]
  name = "github.com/bitly/go-simplejson"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/grafana/grafana_plugin_model"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
