on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: npm install
        run: /usr/bin/docker run --rm -v ${PWD}:/opt/gcds -w /opt/gcds node:11 npm install
      - name: webpack
        run: /usr/bin/docker run --rm -v ${PWD}:/opt/gcds -w /opt/gcds node:11 node node_modules/webpack/bin/webpack.js
      - name: dep ensure
        run: /usr/bin/docker run --rm -v ${PWD}:/go/src/github.com/ha/gcp -w /go/src/github.com/ha/gcp instrumentisto/dep ensure
      - name: go build
        run: /usr/bin/docker run --rm -v ${PWD}:/go/src/github.com/ha/gcp -w /go/src/github.com/ha/gcp golang go build -i -o ./dist/cassandra-plugin_linux_amd64 ./backend
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: './dist/cassandra-plugin_linux_amd64'
